source("get_and_clean_data.R")
datesOfInterest <- get_and_clean_data()
png("Plot3.png")
plot(datesOfInterest[,DateTime],datesOfInterest[,Sub_metering_1],type="n",xlab="",
     ylab="Energy sub metering")
lines(datesOfInterest[,DateTime],datesOfInterest[,Sub_metering_1],col="black")
lines(datesOfInterest[,DateTime],datesOfInterest[,Sub_metering_2],col="red")
lines(datesOfInterest[,DateTime],datesOfInterest[,Sub_metering_3],col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1)
dev.off()